version: "3.7"

services:
  clef-testnet:
    hostname: clef-testnet
    image: clef-testnet
    build:
      context: .
    ports:
      - 8550:8550
    networks:
      priv-eth-net-testnet:

networks:
  priv-eth-net-testnet:
    driver: bridge
    name: priv-eth-net-testnet